/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myjnitest_MainActivity */

#ifndef _Included_com_example_administrator_myjnitest_MainActivity
#define _Included_com_example_administrator_myjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myjnitest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_myjnitest_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_myjnitest_MainActivity
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_myjnitest_MainActivity_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_administrator_myjnitest_MainActivity
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_administrator_myjnitest_MainActivity_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
